# Generated by Django 4.2.24 on 2025-09-28 16:19

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Sharing'), ('triple', 'Triple Sharing'), ('dormitory', 'Dormitory')], max_length=20)),
                ('preferred_floor', models.PositiveIntegerField(blank=True, help_text='Preferred floor number (optional)', null=True)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('guardian_address', models.TextField()),
                ('medical_conditions', models.TextField(blank=True, help_text='Any medical conditions or allergies (optional)')),
                ('dietary_requirements', models.TextField(blank=True, help_text='Special dietary requirements (optional)')),
                ('roommate_preference', models.CharField(blank=True, help_text='Preferred roommate name or any specific requests (optional)', max_length=200)),
                ('special_requests', models.TextField(blank=True, help_text='Any other special requests or requirements')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_comments', models.TextField(blank=True, help_text='Comments from admin when approving/rejecting')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('allocated_room', models.CharField(blank=True, help_text='Room number allocated (filled when approved)', max_length=50)),
                ('allocated_bed', models.CharField(blank=True, help_text='Bed number allocated (filled when approved)', max_length=10)),
            ],
            options={
                'verbose_name': 'Hostel Application',
                'verbose_name_plural': 'Hostel Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('sick', 'Sick Leave'), ('personal', 'Personal Leave'), ('family', 'Family Emergency'), ('academic', 'Academic Purpose'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(help_text='Detailed reason for leave')),
                ('contact_address', models.TextField(help_text='Address where student can be contacted during leave')),
                ('contact_phone', models.CharField(help_text='Phone number during leave', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_comments', models.TextField(blank=True, help_text='Comments from admin when approving/rejecting')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Leave Application',
                'verbose_name_plural': 'Leave Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
