# Generated by Django 4.2.24 on 2025-09-28 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='processed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['Admin', 'Faculty']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_leave_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostelapplication',
            name='processed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['Admin', 'Faculty']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_hostel_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostelapplication',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='hostelapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('student',), name='one_active_hostel_application_per_student'),
        ),
    ]
