# Generated by Django 5.2.6 on 2025-09-17 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_id', models.CharField(max_length=50, unique=True)),
                ('student_id', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('triple', 'Triple Room'), ('dormitory', 'Dormitory')], max_length=20)),
                ('allocated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-allocated_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('triple', 'Triple Room'), ('dormitory', 'Dormitory')], max_length=20, unique=True)),
                ('total_capacity', models.PositiveIntegerField()),
                ('occupied', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Hostel Capacities',
            },
        ),
        migrations.CreateModel(
            name='HostelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50, unique=True)),
                ('student_id', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(max_length=15)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('triple', 'Triple Room'), ('dormitory', 'Dormitory')], max_length=20)),
                ('preferences', models.TextField(blank=True, help_text='Any special preferences or requirements')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
